### ISSUE TITLE
No matched test files! for project compiled with msbuild (.NET 4)

### ISSUE THREAD

**Issue by ikondrasovas** [microsoft/vstest-action#19]
In my workflow file I have defined the following step for test execution, but I get back an "No matched test files" error back:

 

    - name: vstest-action
      uses: microsoft/vstest-action@v1.0.0
      with:
        # Run tests from the specified files
        # testAssembly: # default is **\\*test*.dll\n!**\\*TestAdapter.dll\n!**\\obj\\**
        # Folder to search for the test assemblies
          searchFolder: "D:\\a\\<myapplication>\\source\\clientapp\\<mytestproject>\\bin\\Release\\"

all other parameters contain default values.

I have verified the test .dll file is compiled and available by looking at the logs.
To make sure, I have also fully specified the absolute path where the test .dll is located.

I am wondering if the reason is that the test assembly is .NET 4.0 and it was built using microsoft/setup-msbuild@v1.1 action.

Any ideas on what is the problem or how can I further isolate it?

Thanks!

**Comment by czf** [comment]
I ran into a similar, if not the same, issue and ended up being explicit with the `testAssembly` parameter.  I think the default might be throwing things off.  If you haven't found a resolution maybe give this a shot.

``` yml
- name: Run tests
  uses: microsoft/vstest-action@v1.0.0
  with:
    searchFolder: '.' 
    testAssembly: |
        /**/*test*.dll
        !./**/*TestAdapter.dll
        !./**/obj/**
```
