### ISSUE TITLE
Running the same dll twice

### ISSUE THREAD

**Issue by leandromsft** [microsoft/vstest-action#9]
I'm using this action, but my dll is running twice where it contains the tests.
When I analyzed the execution I verified that the DLL is twice

```
D:\a\_actions\microsoft\vstest-action\v1.0.0\dist\win-x64\VsTest\v160\Common7\IDE\Extensions\TestPlatform\vstest.console.exe 
D:\a\web-application-full-framework\web-application-full-framework\src\WebApplicationFullFramework.UnitTest\bin\Release\WebApplicationFullFramework.UnitTest.dll 
D:\a\web-application-full-framework\web-application-full-framework\src\WebApplicationFullFramework.UnitTest\obj\Release\WebApplicationFullFramework.UnitTest.dll /Logger:TRX
```

My action is configure like bellow

```
- name: Run tests
    uses: microsoft/vstest-action@v1.0.0
    with:
      testAssembly: '**\\WebApplicationFullFramework.UnitTest.dll'
      searchFolder: src\WebApplicationFullFramework.UnitTest\
```
